# Generated by Django 5.2.4 on 2025-08-06 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100, verbose_name='نام تست')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('test_duration', models.IntegerField(verbose_name='مدت زمان تست (دقیقه)')),
                ('total_slots', models.IntegerField(verbose_name='تعداد کل اسلات\u200cها')),
                ('total_reservations', models.IntegerField(verbose_name='تعداد کل رزروها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فرآیند تست',
                'verbose_name_plural': 'فرآیندهای تست',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSlotResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_start', models.TimeField(verbose_name='شروع اسلات')),
                ('slot_end', models.TimeField(verbose_name='پایان اسلات')),
                ('reservations_count', models.IntegerField(verbose_name='تعداد رزروها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('test_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_results', to='testprocces.testprocess', verbose_name='فرآیند تست')),
            ],
            options={
                'verbose_name': 'نتیجه اسلات تست',
                'verbose_name_plural': 'نتایج اسلات\u200cهای تست',
                'ordering': ['slot_start'],
            },
        ),
    ]
