# Generated by Django 5.2.4 on 2025-08-06 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('specialties', models.TextField(verbose_name='رشته\u200cهای تخصصی')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'مربی',
                'verbose_name_plural': 'مربیان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه\u200cشنبه', 'سه\u200cشنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنج\u200cشنبه', 'پنج\u200cشنبه'), ('جمعه', 'جمعه')], max_length=10, verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('athlete_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام ورزشکار')),
                ('gym_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام باشگاه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='coachs.coach', verbose_name='مربی')),
            ],
            options={
                'verbose_name': 'برنامه زمانی مربی',
                'verbose_name_plural': 'برنامه\u200cهای زمانی مربیان',
                'ordering': ['coach', 'day', 'start_time'],
                'unique_together': {('coach', 'day', 'start_time', 'end_time')},
            },
        ),
    ]
