# Generated by Django 5.2.4 on 2025-08-06 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachs', '0001_initial'),
    ]

    operations = [
        # تغییر فیلد day به date
        migrations.RenameField(
            model_name='coachschedule',
            old_name='day',
            new_name='date',
        ),
        # تغییر نوع فیلد از CharField به DateField
        migrations.AlterField(
            model_name='coachschedule',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='تاریخ'),
        ),
        # بروزرسانی ordering
        migrations.AlterModelOptions(
            name='coachschedule',
            options={'ordering': ['coach', 'date', 'start_time'], 'verbose_name': 'برنامه زمانی مربی', 'verbose_name_plural': 'برنامه\u200cهای زمانی مربیان'},
        ),
        # بروزرسانی unique_together
        migrations.AlterUniqueTogether(
            name='coachschedule',
            unique_together={('coach', 'date', 'start_time', 'end_time')},
        ),
    ] 