# Generated by Django 5.2.4 on 2025-08-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachs', '0002_alter_coachschedule_day_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره حساب'),
        ),
    ]
