# Generated by Django 5.2.4 on 2025-08-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachs', '0003_coach_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='username',
            field=models.CharField(default='guest', max_length=50, verbose_name='نام کاربری'),
        ),
    ]
