# Generated by Django 5.2.4 on 2025-08-04 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام باشگاه')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('owner', models.CharField(max_length=100, verbose_name='صاحب باشگاه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'باشگاه',
                'verbose_name_plural': 'باشگاه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه\u200cشنبه', 'سه\u200cشنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنج\u200cشنبه', 'پنج\u200cشنبه'), ('جمعه', 'جمعه')], max_length=10, verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='gyms.gym', verbose_name='باشگاه')),
            ],
            options={
                'verbose_name': 'بازه زمانی',
                'verbose_name_plural': 'بازه\u200cهای زمانی',
                'ordering': ['day', 'start_time'],
                'unique_together': {('gym', 'day', 'start_time', 'end_time')},
            },
        ),
    ]
