# Generated by Django 5.2.4 on 2025-08-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_alter_timeslot_day_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره حساب'),
        ),
    ]
