# Generated by Django 5.2.4 on 2025-08-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twallet', '0001_initial'),
    ]

    operations = [
        # اضافه کردن فیلد username به BuyOrder
        migrations.AddField(
            model_name='buyorder',
            name='username',
            field=models.CharField(default='unknown_user', max_length=150, verbose_name='نام کاربری'),
        ),
        
        # اضافه کردن فیلد username به SellOrder
        migrations.AddField(
            model_name='sellorder',
            name='username',
            field=models.CharField(default='unknown_user', max_length=150, verbose_name='نام کاربری'),
        ),
        
        # اضافه کردن فیلدهای buyer_username و seller_username به Transaction
        migrations.AddField(
            model_name='transaction',
            name='buyer_username',
            field=models.CharField(default='unknown_user', max_length=150, verbose_name='نام کاربری خریدار'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_username',
            field=models.CharField(default='unknown_user', max_length=150, verbose_name='نام کاربری فروشنده'),
        ),
        
        # اضافه کردن فیلدهای buyer_balance_after و seller_balance_after به Transaction
        migrations.AddField(
            model_name='transaction',
            name='buyer_balance_after',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی خریدار پس از تراکنش'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_balance_after',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی فروشنده پس از تراکنش'),
        ),
    ] 