# Generated by Django 5.2.4 on 2025-08-06 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twallet', '0002_add_username_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='نام کاربری')),
                ('tokens', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد توکن\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'موجودی کاربر',
                'verbose_name_plural': 'موجودی کاربران',
            },
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='balance_after',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buyer_balance_after',
            field=models.PositiveIntegerField(verbose_name='موجودی خریدار پس از تراکنش'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller_balance_after',
            field=models.PositiveIntegerField(verbose_name='موجودی فروشنده پس از تراکنش'),
        ),
    ]
