# Generated by Django 5.2.4 on 2025-08-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام تست')),
                ('author', models.CharField(max_length=100, verbose_name='نویسنده (نام باشگاه)')),
                ('average_duration', models.DurationField(verbose_name='مدت زمان میانگین تست')),
                ('sport_type', models.CharField(choices=[('فوتبال', 'فوتبال'), ('بسکتبال', 'بسکتبال'), ('والیبال', 'والیبال'), ('تنیس', 'تنیس'), ('شنا', 'شنا'), ('دوومیدانی', 'دوومیدانی'), ('وزنه\u200cبرداری', 'وزنه\u200cبرداری'), ('کشتی', 'کشتی'), ('بوکس', 'بوکس'), ('کاراته', 'کاراته'), ('تکواندو', 'تکواندو'), ('جودو', 'جودو'), ('ژیمناستیک', 'ژیمناستیک'), ('اسکی', 'اسکی'), ('سایر', 'سایر')], max_length=20, verbose_name='نوع ورزش تست')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'تست ورزشی',
                'verbose_name_plural': 'تست\u200cهای ورزشی',
                'ordering': ['-created_at'],
            },
        ),
    ]
