# Generated by Django 5.2.4 on 2025-08-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporttest',
            name='reward_tokens',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد توکن جایزه'),
        ),
        migrations.AddField(
            model_name='sporttest',
            name='test_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='هزینه تست (تومان)'),
        ),
    ]
