# Generated by Django 5.2.4 on 2025-08-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_sporttest_reward_tokens_sporttest_test_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporttest',
            name='collateral_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد وثیقه'),
        ),
    ]
