# Generated by Django 5.2.4 on 2025-08-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره حساب'),
        ),
    ]
